CREATE GENERATOR CLIENTES;
CREATE GENERATOR PRODUTOS;
CREATE GENERATOR TECNICOS;
CREATE GENERATOR PEDIDOS;
CREATE GENERATOR ITENSPEDIDO;
COMMIT WORK;
CREATE TABLE CLIENTES (
  CLIE_ID INTEGER NOT NULL,
  CLIE_NOME VARCHAR(80) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252,
  CLIE_CPF VARCHAR(14) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252);
COMMIT WORK;
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIE_ID);
ALTER TABLE CLIENTES ADD CONSTRAINT UQ_CLIENTES UNIQUE (CLIE_CPF);

CREATE TABLE PRODUTOS (
  PROD_ID INTEGER NOT NULL,
  PROD_NOME VARCHAR(80) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252,
  PROD_VALOR NUMERIC(13, 2) NOT NULL,
  PROD_CONTROLE CHAR(1) CHARACTER SET WIN1252 DEFAULT 'N' NOT NULL COLLATE WIN1252);
COMMIT WORK;
ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (PROD_ID);
ALTER TABLE PRODUTOS ADD CONSTRAINT UQ_PRODUTOS UNIQUE (PROD_NOME);

CREATE TABLE TECNICOS (
  TECN_ID INTEGER NOT NULL,
  TECN_NOME VARCHAR(80) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252,
  TECN_CPF VARCHAR(14) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252,
  TECN_NR_REGISTRO VARCHAR(25) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252);
COMMIT WORK;
ALTER TABLE TECNICOS ADD CONSTRAINT PK_TECNICOS PRIMARY KEY (TECN_ID);
ALTER TABLE TECNICOS ADD CONSTRAINT UQ_TECNICOS UNIQUE (TECN_CPF,TECN_NR_REGISTRO);

CREATE TABLE ITENSPEDIDO (
  ITEM_ID INTEGER NOT NULL,
  ITEM_PEDI_ID INTEGER NOT NULL,
  ITEM_PROD_ID INTEGER NOT NULL,
  ITEM_QTDADE NUMERIC(13, 2) NOT NULL,
  ITEM_VLRUNIT NUMERIC(13, 2) NOT NULL,
  ITEM_PROD_NOME COMPUTED BY ((SELECT FIRST 1 PRODUTOS.PROD_NOME FROM PRODUTOS WHERE PRODUTOS.PROD_ID = ITENSPEDIDO.ITEM_PROD_ID)),
  ITEM_PROD_CONTROLE COMPUTED BY ((SELECT FIRST 1 PRODUTOS.PROD_CONTROLE FROM PRODUTOS WHERE PRODUTOS.PROD_ID = ITENSPEDIDO.ITEM_PROD_ID)),
  ITEM_TOTAL COMPUTED BY ((ITENSPEDIDO.ITEM_QTDADE*ITENSPEDIDO.ITEM_VLRUNIT))
);
COMMIT WORK;
ALTER TABLE ITENSPEDIDO ALTER COLUMN ITEM_PROD_NOME POSITION 6;
ALTER TABLE ITENSPEDIDO ALTER COLUMN ITEM_TOTAL POSITION 8;
ALTER TABLE ITENSPEDIDO ALTER COLUMN ITEM_PROD_CONTROLE POSITION 7;
ALTER TABLE ITENSPEDIDO ADD CONSTRAINT PK_ITENSPEDIDO PRIMARY KEY (ITEM_ID);
ALTER TABLE ITENSPEDIDO ADD CONSTRAINT FK_ITENSPEDIDO1 FOREIGN KEY (ITEM_PROD_ID) REFERENCES PRODUTOS(PROD_ID) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT WORK;
CREATE TABLE PEDIDOS (
  PEDI_ID INTEGER NOT NULL,
  PEDI_CLIE_ID INTEGER NOT NULL,
  PEDI_DT_CADASTRO DATE DEFAULT CURRENT_DATE,
  PEDI_STATUS CHAR(1) CHARACTER SET WIN1252 DEFAULT 'C' COLLATE WIN1252,
  PEDI_TOTAL COMPUTED BY ((SELECT SUM(ITENSPEDIDO.ITEM_QTDADE*ITENSPEDIDO.ITEM_VLRUNIT) FROM ITENSPEDIDO WHERE ITENSPEDIDO.ITEM_PEDI_ID = PEDIDOS.PEDI_ID)),
  PEDI_CLIE_NOME COMPUTED BY ((SELECT FIRST 1 CLIENTES.CLIE_NOME FROM CLIENTES WHERE CLIENTES.CLIE_ID = PEDIDOS.PEDI_CLIE_ID)),
  PEDI_CLIE_CPF COMPUTED BY ((SELECT FIRST 1 CLIENTES.CLIE_CPF FROM CLIENTES WHERE CLIENTES.CLIE_ID = PEDIDOS.PEDI_CLIE_ID)),
  PEDI_TECN_NOME COMPUTED BY ((SELECT FIRST 1 TECN_NOME FROM TECNICOS WHERE TECN_ID = PEDIDOS.PEDI_TECN_ID)),
  PEDI_TECN_CPF COMPUTED BY ((SELECT FIRST 1 TECN_CPF FROM TECNICOS WHERE TECN_ID = PEDIDOS.PEDI_TECN_ID)),
  PEDI_TECN_NR_REGISTRO COMPUTED BY ((SELECT FIRST 1 TECN_NR_REGISTRO FROM TECNICOS WHERE TECN_ID = PEDIDOS.PEDI_TECN_ID)),
  PEDI_ASSINADO CHAR(1) DEFAULT 'S',
  PEDI_TECN_ID INTEGER
);
COMMIT;
ALTER TABLE PEDIDOS ALTER COLUMN PEDI_CLIE_NOME POSITION 6;
ALTER TABLE PEDIDOS ALTER COLUMN PEDI_CLIE_CPF POSITION 7;
ALTER TABLE PEDIDOS ADD CONSTRAINT PK_PEDIDOS PRIMARY KEY (PEDI_ID);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS FOREIGN KEY (PEDI_CLIE_ID) REFERENCES CLIENTES(CLIE_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PEDIDOS ADD CONSTRAINT UQ_PEDIDOS UNIQUE (PEDI_ID,PEDI_CLIE_ID);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS1 FOREIGN KEY (PEDI_TECN_ID) REFERENCES TECNICOS(TECN_ID);
ALTER TABLE ITENSPEDIDO ADD CONSTRAINT FK_ITENSPEDIDO FOREIGN KEY (ITEM_PEDI_ID) REFERENCES PEDIDOS(PEDI_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ITENSPEDIDO ADD CONSTRAINT UQ_ITENSPEDIDO UNIQUE (ITEM_ID,ITEM_PEDI_ID);
COMMIT WORK;
UPDATE OR INSERT INTO TECNICOS(TECN_ID,TECN_NOME,TECN_CPF,TECN_NR_REGISTRO) 
VALUES(1,'TECNICO AGRICOLA I','746.092.150-55','123456');
UPDATE OR INSERT INTO TECNICOS(TECN_ID,TECN_NOME,TECN_CPF,TECN_NR_REGISTRO) 
VALUES(2,'TECNICO AGRICOLA II','471.714.850-99','321654');
UPDATE OR INSERT INTO TECNICOS(TECN_ID,TECN_NOME,TECN_CPF,TECN_NR_REGISTRO) 
VALUES(3,'TECNICO AGRICOLA III','589.436.710-75','951847');
COMMIT WORK;